# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-datadog-synthetics-private-location
  description: This component provisions a Datadog synthetics private location on Datadog and a private location agent on EKS cluster
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
